### ISSUE TITLE
Adding icons to Timer CSS layouts.

### ISSUE THREAD

**Issue by alkaris2** [3snowp7im/urn#52]
As title states, should to be able to add icons to splits from CSS layouts by pointing to an image directory for the themes and then self-define the icon names for the JSON file, ie;

CSS Theme file could be using

```CSS
/* Match class with name "icon" in its name */
[class^="icon"] {
  width: 50px;
  height: 50px;
  position: relative;
  top: 15px;
  margin-right: 10px;
  fill: #000;
  background-repeat: no-repeat;
}
```

and JSON file could also have

```JSON
{
  "title": "<game_title_here> Any%",
  "attempt_count": 74,
  "splits": [
    {
      "icons": "../images/icon_1.png",
      "title": "<split_name>",
      "time": "12:12:59.927",
      "best_time": "12:12:59.927",
      "best_segment": "12:12:59.927"
    }
  ],
  "width": 318,
  "height": 282
}
```
